### ISSUE TITLE
The problem about JsonTest::testThrowOnMaximumDepthExceeded exception

### ISSUE THREAD

**Issue by peter279k** [Innmind/Json#6]
As title, when running PHPUnit tests on Travis CI build, it will be the `Innmind\Json\Exception\MaximumDepthExceeded` exception class throwing.

When I run PHPUnit tests on my local development environment, I get following exception assertion failed:

```Bash
1) Tests\Innmind\Json\JsonTest::testThrowOnMaximumDepthExceeded
Failed asserting that exception of type "Error" matches expected exception "Innmind\Json\Exception\MaximumDepthExceeded". Message was: "Maximum function nesting level of '256' reached, aborting!"
```

I have no idea about why this error happens.

After checking the PHP versions, my PHP version on local development environment is same as Travis development environment. They're `PHP 7.3.21`.

To resolve this issue, I think we can use the `try.....catch` block to catch different exceptions and avoid unexpected exception assertion.

**Comment by Baptouuuu** [comment]
Hi,

The problem is due to xdebug having a maximum nested calls of `256` which is lower than the default depth of `512` configured for the nesting of json elements.

To change this configuration you need to modify the php configuration key `xdebug.max_nesting_level` as done here https://github.com/Innmind/Json/blob/develop/.github/workflows/ci.yml#L22. You could also completely disable xdebug locally
